using UnityEngine;
using UnityEngine.UI;

public class DAZCharacterTextureControlUI : UIProvider
{
	public Text uvLabel;

	public Button faceDiffuseFileBrowseButton;

	public Button faceDiffuseReloadButton;

	public Button faceDiffuseClearButton;

	public Text faceDiffuseUrlText;

	public Button torsoDiffuseFileBrowseButton;

	public Button torsoDiffuseReloadButton;

	public Button torsoDiffuseClearButton;

	public Text torsoDiffuseUrlText;

	public Button limbsDiffuseFileBrowseButton;

	public Button limbsDiffuseReloadButton;

	public Button limbsDiffuseClearButton;

	public Text limbsDiffuseUrlText;

	public Button genitalsDiffuseFileBrowseButton;

	public Button genitalsDiffuseReloadButton;

	public Button genitalsDiffuseClearButton;

	public Text genitalsDiffuseUrlText;

	public Button faceSpecularFileBrowseButton;

	public Button faceSpecularReloadButton;

	public Button faceSpecularClearButton;

	public Text faceSpecularUrlText;

	public Button torsoSpecularFileBrowseButton;

	public Button torsoSpecularReloadButton;

	public Button torsoSpecularClearButton;

	public Text torsoSpecularUrlText;

	public Button limbsSpecularFileBrowseButton;

	public Button limbsSpecularReloadButton;

	public Button limbsSpecularClearButton;

	public Text limbsSpecularUrlText;

	public Button genitalsSpecularFileBrowseButton;

	public Button genitalsSpecularReloadButton;

	public Button genitalsSpecularClearButton;

	public Text genitalsSpecularUrlText;

	public Button faceGlossFileBrowseButton;

	public Button faceGlossReloadButton;

	public Button faceGlossClearButton;

	public Text faceGlossUrlText;

	public Button torsoGlossFileBrowseButton;

	public Button torsoGlossReloadButton;

	public Button torsoGlossClearButton;

	public Text torsoGlossUrlText;

	public Button limbsGlossFileBrowseButton;

	public Button limbsGlossReloadButton;

	public Button limbsGlossClearButton;

	public Text limbsGlossUrlText;

	public Button genitalsGlossFileBrowseButton;

	public Button genitalsGlossReloadButton;

	public Button genitalsGlossClearButton;

	public Text genitalsGlossUrlText;

	public Button faceNormalFileBrowseButton;

	public Button faceNormalReloadButton;

	public Button faceNormalClearButton;

	public Text faceNormalUrlText;

	public Button torsoNormalFileBrowseButton;

	public Button torsoNormalReloadButton;

	public Button torsoNormalClearButton;

	public Text torsoNormalUrlText;

	public Button limbsNormalFileBrowseButton;

	public Button limbsNormalReloadButton;

	public Button limbsNormalClearButton;

	public Text limbsNormalUrlText;

	public Button genitalsNormalFileBrowseButton;

	public Button genitalsNormalReloadButton;

	public Button genitalsNormalClearButton;

	public Text genitalsNormalUrlText;

	public Button faceDetailFileBrowseButton;

	public Button faceDetailReloadButton;

	public Button faceDetailClearButton;

	public Text faceDetailUrlText;

	public Button torsoDetailFileBrowseButton;

	public Button torsoDetailReloadButton;

	public Button torsoDetailClearButton;

	public Text torsoDetailUrlText;

	public Button limbsDetailFileBrowseButton;

	public Button limbsDetailReloadButton;

	public Button limbsDetailClearButton;

	public Text limbsDetailUrlText;

	public Button genitalsDetailFileBrowseButton;

	public Button genitalsDetailReloadButton;

	public Button genitalsDetailClearButton;

	public Text genitalsDetailUrlText;

	public Button faceDecalFileBrowseButton;

	public Button faceDecalReloadButton;

	public Button faceDecalClearButton;

	public Text faceDecalUrlText;

	public Button torsoDecalFileBrowseButton;

	public Button torsoDecalReloadButton;

	public Button torsoDecalClearButton;

	public Text torsoDecalUrlText;

	public Button limbsDecalFileBrowseButton;

	public Button limbsDecalReloadButton;

	public Button limbsDecalClearButton;

	public Text limbsDecalUrlText;

	public Button genitalsDecalFileBrowseButton;

	public Button genitalsDecalReloadButton;

	public Button genitalsDecalClearButton;

	public Text genitalsDecalUrlText;

	public Button directoryBrowseButton;

	public Toggle autoBlendGenitalTexturesToggle;

	public Toggle autoBlendGenitalSpecGlossNormalTexturesToggle;

	public Button dumpAutoGeneratedGenitalTexturesButton;

	public Button autoBlendGenitalDiffuseTextureButton;

	public Transform autoBlendGenitalColorAdjustContainer;

	public Slider autoBlendGenitalLightenDarkenSlider;

	public Slider autoBlendGenitalHueOffsetSlider;

	public Slider autoBlendGenitalSaturationOffsetSlider;
}
